### ISSUE TITLE
[BUG] - User DB seeder

### ISSUE THREAD

**Issue by Nejcc** [eporsche/daybreak#12]
There is a problem with user DB seeder when you change email and password  inside ```DatabaseSeeder```

```php
app(CreatesNewUsers::class)->create([
            'name' => 'Admin User',
            'email' => 'admin@daybreak.corp',
            'password' => 'admin1234',
            'password_confirmation' => 'admin1234',
            'terms' => Jetstream::hasTermsAndPrivacyPolicyFeature() ? true : false,
        ]);
```

**Comment by FelixBoers** [comment]
Hi Nejcc,

Thanks for your interest in this project.
What exactly is your problem here? I changed the email and password to something else and then executed `./vendor/bin/sail artisan db:seed` without any problems. 

However, I noticed two things that might help you further:
1. Verify that `password` and `password_confirmation` are equal.
2. Verify that there is no other user registered with the same `email`.

**Comment by nejcdev** [comment]
Why you dont use ```bcrypt('admin1234')``` on password ?

**Comment by Nejcc** [comment]
@FelixBoers   i will try to check  i just check  or fly trough the project and see some issues

**Comment by FelixBoers** [comment]
@nejcdev Because then it would be encrypted twice
@Nejcc Thanks for your reply. If you still have an issue, please open this ticket again.
