### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ugintl** [eporsche/daybreak#34]
1. Is it available in english? The demo is not english.

2. Is it necessary to use this command "./vendor/bin/sail"?

**Comment by eporsche** [comment]
1. Not out of the box . You have to re-implement the GermanDateFormatter. For example as UKDateformatter and register it as the implementation in the [AppServiceProvider](https://github.com/eporsche/daybreak/blob/eae388cf850926166e5b3324c01534b87252060f/app/Providers/AppServiceProvider.php#L83) Otherwise you will get validation errors. Apart from that you have to make sure that within the app config (app.php) the locale is set to 'en' and the timezone is set to your location.
2. No - you can setup the software as a regular laravel application and use any deployment method you want.
